[gcp_service_account]
type = "service_account"
project_id = "api-nps-469521"
private_key_id = "c485fc82159a79aaa85ddfa6eabf74d0472b60b7"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCkuH6es30vCjk7
9arpFP2x7NG+3dVW2QM1WRy/aZ2uCnYC6qjG7YTirErAQE2V6+oZywkKK/ojB/aY
fEYarvuqcEom7EPMZWqeIVVwReLpW430VO//n5DVXhf5likBLWFK29NcG57SqWRk
Mr17peN4b0IlGuWdGpJwe9tzGPXOq7aU+QBiyuqBmSpIz6x9aB+cjEOYx+rJ5UK/
4P2TNM/Iwmbdrlzndra3uRE/+CMCQoPwyXQmLBfPBUDcaLDNnn59zqgVn+Y3OcM/
oDPidEjlKnhtluX3Ynhq8bVa4oc9ggYwqDI2K15QZ82GlTt/bDMRsUX9fivw8pil
aUIQVg+bAgMBAAECggEAAk0Pe8EPIR6X8RX79riT2K3xuiRYLBfo+xBNHgFoMfu0
bVMA25KK1i3I94mOa+c5RHX5INq/akjcsYGe6xWBr35VEtkfE1ZhWGcnzeM0CcV9
JKohFiWQ/OINHK/zz6/mGYkbmUBLhi7Wl627xuPo2xBW0LTg+0JZRFf+l0uEd4gZ
zpE0c5X+eMDYS1iyl09XKvv9S1foUn/QTy5N5BZkmyHA/iPCPaP4rHeZgu0t5dOh
TxBioqoEiwsotszJuhdTr8z7eVayVxudm4q1Ssa3zi8giqxZ+kMz0tcEgWytMVv2
Cmz8k2jgNEvLA84wTZgQcAPR7Fkga6vzin1jGEJB3QKBgQDO9ZHyUCzeTBOe+mjX
MfCmbVhJuLHBPC/Xyzny9l8qtKkpX/2+1d00MMwpZlSBXcm6YF9dChMxkQZkIhl7
Nim6JPcspuXypDW0gaGzIrRWkt9Ho7HnsXcINoJqiH5PWdNDgCxv2CTaKi0XmM9P
eOmvu6ftQgoW4NEC+4qE7E6TLQKBgQDLwKzRLBQst3XfJC4WBtZGD7Nop69aPCit
pguMQDK1Aqk2z0Vpzm3wk/3URNLMSL7vrdxnEdkWCqCOKeFylZ+cvnCAhBH8BI6x
cSXWUdpZQI5gzQATNqEsPkQiAyLAnibjk9BYsljVwLmTOjHUCcM8/MNRIp9ZfRUU
6Tnfxh2K5wKBgQC9reIqZIMK5kzhWv31pQa7ceIGBymbQe9TZyZgYJ+OQ2/6xMiK
O/Z12/dyRiBTRMMbdzJP0mkO960U3w/dliGeQjzsBrcfsJKsMlciGD+STSAox4XJ
JSREOblDrH+feGMhLXsMstvru9YCF4KBgv8imenpkKowl7HYevRUqUPGrQKBgD07
+rQiey21NUeKqA8Wnu8PaOva+Wg1DESj0nSkFpkv44sFX+cckw3qbC6PQIsEkd2W
ctbHFmb5aqdPDuJQ9Vc2JLl696y18eyCBM0UbHrGXAPbmFot4OJbFD7kkl0xKp7a
nZMKhog3E46bvr3q8TIzBMAtl5ZdcSiHr00BTX+hAoGADzsvWxB1x2JV1vy9tpY4
5fCCfdzE7DbzsRTQuwM40aLacHdBBZZOyE+pnZS4M7Dmzt/DnMh2U60DssvnvaRC
8yrNUs5Z6DIik+z+SW2k0eqeqtdKV26QxTM3xGwQJ/MVpN4nOcKA+tQde+3mqPvR
tPbOpYHlVUFcgUB3Q2S1RpI=
-----END PRIVATE KEY-----"""
client_email = "api-489@api-nps-469521.iam.gserviceaccount.com"
client_id = "109125966765022947800"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/api-489%40api-nps-469521.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
